### ISSUE TITLE
Ripples from ListItems are not deleted

### ISSUE THREAD

**Issue by lassesteffen** [hpi-swa-teaching/MaterialDesignWidgets#118]
The same is true for MenuItems, but there is a hacky workaround avoiding that.

## Reproduce
1. Click on a ListItem and keep mouseDown
2. Draw mouse out of the list items bounds with mouse still down
3. mouse up

Result: The ripple of the clicked item will not be removed.

**Comment by lassesteffen** [comment]
Idea: Redirection of mouseUp Event needs to be fixed

**Comment by LucPrestin** [comment]
4h gedauert (2 Personen), geschätzt 16
