### ISSUE TITLE
PluggableList problems

### ISSUE THREAD

**Issue by lassesteffen** [hpi-swa-teaching/MaterialDesignWidgets#126]
- [x] Strg  + f does not work
- [x] keyboard focus bugs
- [ ] deselect on second click not working
- [ ] Git Browser does not work with MDPluggableList

**Comment by tom95** [comment]
"Searchable List" issue not accepted yet, because focus cannot always be acquired, thus not allowing to filter.

**Comment by tom95** [comment]
GitBrowser project list shows placeholder text
