### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by CarolinGoerke** [hpi-swa-teaching/MaterialDesignWidgets#8]
As a user I want to pick a primary and secondary color from the predefined colors. The color scheme should include the primary and secondary color and the colors a bit lighter and darker. 
The result includes whether to use light or dark text.

**Comment by TheNotoriousGit** [comment]
See: https://color.adobe.com/de/create/color-wheel/

**Comment by LucPrestin** [comment]
Geplante Käsekuchen: 8
